# Generated by Django 2.2 on 2020-05-13 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Centermaster', '0002_auto_20200512_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridortable',
            name='Corridor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Centermaster.Center_Master'),
        ),
        migrations.AlterField(
            model_name='roomtable',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Centermaster.Center_Master'),
        ),
        migrations.AlterField(
            model_name='toilettable',
            name='Toilet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Centermaster.Center_Master'),
        ),
    ]
